import { motion } from "framer-motion";

const technologies = [
  { name: "React", color: "text-blue-400" },
  { name: "Next.js", color: "text-gray-100" },
  { name: "Flutter", color: "text-blue-500" },
  { name: "Node.js", color: "text-green-500" },
  { name: "TypeScript", color: "text-blue-600" },
  { name: "Python", color: "text-blue-400" },
  { name: "PostgreSQL", color: "text-blue-600" },
  { name: "MongoDB", color: "text-green-500" },
  { name: "AWS", color: "text-orange-400" },
  { name: "Google Cloud", color: "text-red-500" },
  { name: "Azure", color: "text-blue-500" },
  { name: "Firebase", color: "text-yellow-400" },
  { name: "Supabase", color: "text-green-600" },
  { name: "Vercel", color: "text-gray-100" },
  { name: "Netlify", color: "text-teal-400" },
  { name: "Docker", color: "text-blue-500" },
  { name: "Kubernetes", color: "text-blue-600" },
  { name: "Redis", color: "text-red-500" },
  { name: "GraphQL", color: "text-pink-500" },
  { name: "REST API", color: "text-green-400" },
  { name: "Stripe", color: "text-purple-500" },
  { name: "OpenAI", color: "text-green-400" },
  { name: "TensorFlow", color: "text-orange-500" },
  { name: "Git", color: "text-red-500" },
  { name: "GitHub", color: "text-gray-100" },
  { name: "VS Code", color: "text-blue-500" },
  { name: "Tailwind CSS", color: "text-cyan-400" },
  { name: "Bootstrap", color: "text-purple-600" },
  { name: "Material UI", color: "text-blue-400" },
  { name: "Chart.js", color: "text-red-400" },
  { name: "D3.js", color: "text-orange-400" },
  { name: "Three.js", color: "text-gray-100" },
  { name: "WebGL", color: "text-gray-100" },
  { name: "Socket.io", color: "text-gray-100" },
  { name: "JWT", color: "text-gray-100" },
  { name: "OAuth", color: "text-gray-100" },
  { name: "SSL/TLS", color: "text-green-500" },
  { name: "HTTP/3", color: "text-blue-400" },
  { name: "WebSocket", color: "text-yellow-400" },
  { name: "PWA", color: "text-blue-500" },
  { name: "Service Worker", color: "text-gray-100" },
  { name: "IndexedDB", color: "text-yellow-600" },
  { name: "WebAssembly", color: "text-purple-500" },
  { name: "Sass", color: "text-pink-400" },
  { name: "Webpack", color: "text-blue-600" },
  { name: "Vite", color: "text-purple-500" },
  { name: "ESLint", color: "text-purple-400" },
  { name: "Jest", color: "text-red-600" },
  { name: "Cypress", color: "text-teal-400" },
  { name: "Storybook", color: "text-pink-500" },
  { name: "Figma", color: "text-purple-500" },
  { name: "Adobe XD", color: "text-pink-600" },
  { name: "Sketch", color: "text-orange-400" },
  { name: "Canva", color: "text-blue-400" },
  { name: "Slack", color: "text-purple-500" },
  { name: "Discord", color: "text-indigo-500" },
  { name: "Zoom", color: "text-blue-500" },
  { name: "Jira", color: "text-blue-600" },
  { name: "Trello", color: "text-blue-400" },
  { name: "Asana", color: "text-pink-500" },
  { name: "Notion", color: "text-gray-100" },
  { name: "Linear", color: "text-gray-100" },
  { name: "Vercel Analytics", color: "text-gray-100" },
  { name: "Google Analytics", color: "text-yellow-500" },
  { name: "Hotjar", color: "text-pink-500" },
  { name: "Sentry", color: "text-purple-500" },
  { name: "LogRocket", color: "text-red-500" },
  { name: "Datadog", color: "text-purple-600" },
  { name: "New Relic", color: "text-green-500" },
  { name: "Heroku", color: "text-purple-600" },
  { name: "DigitalOcean", color: "text-blue-500" },
  { name: "Cloudflare", color: "text-orange-500" },
  { name: "Fastly", color: "text-red-500" },
  { name: "Akamai", color: "text-orange-400" },
  { name: "CDN", color: "text-gray-100" },
  { name: "CI/CD", color: "text-green-500" },
  { name: "GitHub Actions", color: "text-gray-100" },
  { name: "GitLab CI", color: "text-orange-500" },
  { name: "Jenkins", color: "text-gray-100" },
  { name: "Travis CI", color: "text-red-500" },
  { name: "CircleCI", color: "text-gray-100" },
  { name: "Bitbucket", color: "text-blue-600" },
  { name: "npm", color: "text-red-500" },
  { name: "Yarn", color: "text-blue-500" },
  { name: "pnpm", color: "text-fuchsia-500" },
  { name: "Babel", color: "text-yellow-500" },
  { name: "ES6+", color: "text-yellow-400" },
  { name: "CSS3", color: "text-blue-500" },
  { name: "HTML5", color: "text-orange-500" },
  { name: "JavaScript", color: "text-yellow-400" },
  { name: "ESLint", color: "text-purple-400" },
  { name: "Prettier", color: "text-pink-400" },
  { name: "Husky", color: "text-orange-600" },
  { name: "lint-staged", color: "text-green-500" },
  { name: "Commitizen", color: "text-blue-400" },
  { name: "Semantic Release", color: "text-gray-100" },
  { name: "Auto-changelog", color: "text-blue-500" },
  { name: "Conventional Commits", color: "text-gray-100" },
  { name: "Monorepo", color: "text-purple-500" },
  { name: "Microservices", color: "text-blue-400" },
  { name: "Serverless", color: "text-orange-500" },
  { name: "Jamstack", color: "text-gray-100" },
  { name: "Headless CMS", color: "text-purple-400" },
  { name: "Strapi", color: "text-gray-100" },
  { name: "Contentful", color: "text-blue-500" },
  { name: "Sanity", color: "text-red-500" },
  { name: "Storyblok", color: "text-pink-500" },
  { name: "Netlify CMS", color: "text-teal-400" },
  { name: "Prismic", color: "text-gray-100" },
  { name: "Cosmic", color: "text-blue-600" },
  { name: "Forestry", color: "text-green-500" },
  { name: "DatoCMS", color: "text-red-600" },
  { name: "Agility CMS", color: "text-purple-500" },
  { name: "Kontent.ai", color: "text-blue-400" },
  { name: "ButterCMS", color: "text-yellow-500" },
  { name: "GraphCMS", color: "text-pink-400" },
  { name: "Craft CMS", color: "text-red-500" },
  { name: "Statamic", color: "text-orange-400" },
  { name: "Kirby", color: "text-pink-600" },
  { name: "Wagtail", color: "text-yellow-600" },
  { name: "Django", color: "text-green-600" },
  { name: "Flask", color: "text-gray-100" },
  { name: "Ruby on Rails", color: "text-red-600" },
  { name: "Laravel", color: "text-red-500" },
  { name: "Symfony", color: "text-gray-100" },
  { name: "Express.js", color: "text-gray-100" },
  { name: "Fastify", color: "text-gray-100" },
  { name: "Koa", color: "text-gray-100" },
  { name: "NestJS", color: "text-red-600" },
  { name: "Svelte", color: "text-orange-500" },
  { name: "Solid.js", color: "text-blue-600" },
  { name: "Qwik", color: "text-blue-400" },
  { name: "Alpine.js", color: "text-gray-100" },
  { name: "HTMX", color: "text-orange-600" },
  { name: "Spring Boot", color: "text-green-600" },
  { name: ".NET", color: "text-purple-600" },
  { name: "Java", color: "text-red-600" },
  { name: "C#", color: "text-purple-600" },
  { name: "Go", color: "text-cyan-500" },
  { name: "Rust", color: "text-orange-600" },
  { name: "Swift", color: "text-orange-500" },
  { name: "Kotlin", color: "text-purple-600" },
  { name: "Scala", color: "text-red-600" },
  { name: "Elixir", color: "text-purple-500" },
  { name: "Erlang", color: "text-red-500" },
  { name: "Clojure", color: "text-blue-600" },
  { name: "Haskell", color: "text-purple-500" },
  { name: "F#", color: "text-blue-500" },
  { name: "R", color: "text-blue-400" },
  { name: "MATLAB", color: "text-orange-500" },
  { name: "Julia", color: "text-purple-600" },
  { name: "Dart", color: "text-blue-500" },
  { name: "Lua", color: "text-blue-600" },
  { name: "Perl", color: "text-purple-500" },
  { name: "PHP", color: "text-purple-600" },
  { name: "WordPress", color: "text-blue-500" },
  { name: "Drupal", color: "text-blue-600" },
  { name: "Magento", color: "text-orange-500" },
  { name: "Shopify", color: "text-green-600" },
  { name: "WooCommerce", color: "text-purple-600" },
  { name: "BigCommerce", color: "text-yellow-500" },
  { name: "Salesforce", color: "text-blue-400" },
  { name: "HubSpot", color: "text-orange-500" },
  { name: "Marketo", color: "text-purple-600" },
  { name: "Pardot", color: "text-red-500" },
  { name: "Mailchimp", color: "text-yellow-500" },
  { name: "Constant Contact", color: "text-blue-500" },
  { name: "ConvertKit", color: "text-purple-500" },
  { name: "ActiveCampaign", color: "text-orange-500" },
  { name: "Klaviyo", color: "text-yellow-600" },
  { name: "Braze", color: "text-purple-500" },
  { name: "Segment", color: "text-green-500" },
  { name: "Mixpanel", color: "text-blue-500" },
  { name: "Amplitude", color: "text-blue-600" },
  { name: "FullStory", color: "text-red-500" },
  { name: "LogRocket", color: "text-red-600" },
  { name: "Hotjar", color: "text-pink-600" },
  { name: "Clarity", color: "text-blue-400" },
  { name: "Crazy Egg", color: "text-red-500" },
  { name: "Optimizely", color: "text-blue-500" },
  { name: "VWO", color: "text-orange-500" },
  { name: "Google Optimize", color: "text-red-500" },
  { name: "Adobe Analytics", color: "text-red-600" },
  { name: "IBM Analytics", color: "text-blue-600" },
  { name: "SAP Analytics", color: "text-blue-500" },
  { name: "Tableau", color: "text-blue-400" },
  { name: "Power BI", color: "text-yellow-600" },
  { name: "Looker", color: "text-gray-100" },
  { name: "Metabase", color: "text-purple-500" },
  { name: "Superset", color: "text-blue-500" },
  { name: "Grafana", color: "text-orange-500" },
  { name: "Kibana", color: "text-yellow-500" },
  { name: "Splunk", color: "text-orange-600" },
  { name: "ELK Stack", color: "text-green-500" },
  { name: "Prometheus", color: "text-red-500" },
  { name: "Grafana", color: "text-orange-500" },
  { name: "Jaeger", color: "text-yellow-600" },
  { name: "Zipkin", color: "text-red-500" },
  { name: "OpenTelemetry", color: "text-gray-100" },
  { name: "Istio", color: "text-blue-500" },
  { name: "Linkerd", color: "text-orange-500" },
  { name: "Consul", color: "text-red-500" },
  { name: "Vault", color: "text-yellow-600" },
  { name: "Nomad", color: "text-teal-500" },
  { name: "Packer", color: "text-blue-600" },
  { name: "Terraform", color: "text-purple-500" },
  { name: "Ansible", color: "text-red-500" },
  { name: "Puppet", color: "text-orange-500" },
  { name: "Chef", color: "text-red-600" },
  { name: "SaltStack", color: "text-blue-500" },
  { name: "Nagios", color: "text-orange-600" },
  { name: "Zabbix", color: "text-red-500" },
  { name: "Prometheus", color: "text-orange-500" },
  { name: "Grafana", color: "text-orange-600" },
  { name: "Kafka", color: "text-gray-100" },
  { name: "RabbitMQ", color: "text-orange-500" },
  { name: "ActiveMQ", color: "text-red-500" },
  { name: "Apache", color: "text-red-600" },
  { name: "Nginx", color: "text-green-600" },
  { name: "Caddy", color: "text-blue-500" },
  { name: "Envoy", color: "text-red-500" },
  { name: "HAProxy", color: "text-red-600" },
  { name: "Traefik", color: "text-orange-600" }
];

const LogoStrip = () => {
  return (
    <section className="py-12 border-y border-border/30 overflow-hidden">
      <div className="container mx-auto px-4 mb-6">
        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center text-sm text-muted-foreground font-medium"
        >
          Trusted technologies powering our solutions
        </motion.p>
      </div>
      
      {/* Infinite scroll */}
      <div className="relative">
        <div className="absolute left-0 top-0 bottom-0 w-20 bg-gradient-to-r from-background to-transparent z-10" />
        <div className="absolute right-0 top-0 bottom-0 w-20 bg-gradient-to-l from-background to-transparent z-10" />
        
        <motion.div
          className="flex gap-8 items-center"
          animate={{ x: [0, -2000] }}
          transition={{ duration: 45, repeat: Infinity, ease: "linear" }}
        >
          {[...technologies, ...technologies, ...technologies].map((tech, i) => (
            <div
              key={`${tech.name}-${i}`}
              className="flex items-center justify-center shrink-0 px-4 py-2 rounded-lg bg-card/30 border border-border/20 hover:bg-card/50 transition-all duration-300 hover:scale-105"
            >
              <span className={`text-sm font-bold ${tech.color} whitespace-nowrap tracking-wide`}>
                {tech.name}
              </span>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default LogoStrip;
